version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: python3 -m venv venv
      - run: source venv/bin/activate
      - run: pip install -r requirements.txt
      - run: pytest
  deploy:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - deploy:
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/flaskeddit.git master
workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master